# Generated by Django 4.0.3 on 2022-05-06 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=10, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate2_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='하위 카테고리')),
                ('P_cate_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cate2_Parents_name', to='notes.category', verbose_name='상위 카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성시간')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('ref_link', models.URLField(blank=True, max_length=300, null=True, verbose_name='참조링크')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Note_Category_name', to='notes.category2', verbose_name='카테고리')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Note_Created_User', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
