# Generated by Django 4.0.3 on 2022-05-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='HTag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='태그'),
        ),
    ]
