# Generated by Django 4.0.3 on 2022-05-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_htag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='HTag',
            new_name='htag',
        ),
    ]
