# Generated by Django 4.0.3 on 2022-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_htag_note_htag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagsave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htag', models.CharField(blank=True, max_length=10, null=True, verbose_name='태그')),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='htag',
        ),
        migrations.AlterField(
            model_name='category',
            name='cate_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='cate2_name',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='하위 카테고리'),
        ),
    ]
