# Generated by Django 4.0.3 on 2022-05-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_category_created_by_category2_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='category2',
            name='cate2_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='하위 카테고리'),
        ),
    ]
